version: '3.8'

services:
  mysql:
    image: mysql:9.4
    container_name: query-builder-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: queryuser
      MYSQL_PASSWORD: querypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 20s
      retries: 10
    networks:
      - query-builder-network

  # Sakila Demo Database (separate container)
  mysql-sakila:
    image: servatj/sakila-mysql:latest
    container_name: sakila
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: queryuser
      MYSQL_PASSWORD: querypass
      MYSQL_DATABASE: sakila
    ports:
      - "3310:3306"
    volumes:
      - sakila_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 20s
      retries: 10
    networks:
      - query-builder-network


volumes:
  mysql_data:
    driver: local
  sakila_data:
    driver: local

networks:
  query-builder-network:
    driver: bridge
